### ISSUE TITLE
[PROBLEM] iRobot Roomba 966

### ISSUE THREAD

**Issue by smarteule** [iobroker-community-adapters/ioBroker.roomba#1]
Hallo,

ich habe im Adapter roomba gelesen, dass der Roomba 966 nur bis Firmware v2.4.6-3 unterstützt wird.

Leider hat mein oben genannter Sauger die FW v2.4.8-44.
Die Anbindung erfolgte soweit problemlos im Adapter, aber bei der Auswertungsanzeige wird nicht alles unterstützt bzw. angezeigt. Des Weiteren ist es nicht möglich die Karte abzurufen.

**Meine Frage:
Kann man ein Firmware Downgrade machen oder wird oben genannte Firmware irgendwann unterstützt?**

**Comment by Zefau** [comment]
Der Anleitung bist du gefolgt, siehe https://github.com/iobroker-community-adapters/ioBroker.roomba#installation ? 

`canvas` muss installiert sein, damit eine Karte gezeichnet wird.

**Comment by Zefau** [comment]
@smarteule
