### ISSUE TITLE
How to manage 2 devices

### ISSUE THREAD

**Issue by DeadBoolean** [iobroker-community-adapters/ioBroker.roomba#10]
Hello, 

i've got 2 irobot devices. 
I managed it using two instances of the adapter, but the webinterface shows only the fist one. 
Is there another way to get 2 devices working with the adapter and using the webinterface to control both? 

Regards

**Comment by wuliwux** [comment]
hi, i have two instances of the adapter running and no problem. which web interface do you mean?

**Comment by mcm1957** [comment]
no  activity since 2020. Lets close here,.
If this is a issue and does still exist with newest adapter release (1.2.1) please open a new issue.
