### ISSUE TITLE
Roomba 966 with Firmware 2.4.13-199 not working

### ISSUE THREAD

**Issue by JonasRueter** [iobroker-community-adapters/ioBroker.roomba#151]
* Roomba Model: Roomba 966
* Roomba Software Version: 2.4.13-199

According to the iRobot-App there is no available software update. the adaptor should be working with 2.4.6-3, but somehow the recognition with the 2.4.13-199 does not seem to work.
Log outputs the following:

roomba.0 | 2023-08-07 10:43:15.048 | info | State value to set for "roomba.0.states._connected" has to be type "string" but received type "boolean"
-- | -- | -- | --
roomba.0 | 2023-08-07 10:43:15.005 | info | State value to set for "roomba.0.states._connected" has to be type "string" but received type "boolean"
roomba.0 | 2023-08-07 10:43:14.939 | warn | Secure Connection to Roomba failed!
roomba.0 | 2023-08-07 10:43:14.938 | info | Roomba Connection closed.
roomba.0 | 2023-08-07 10:43:14.936 | warn | Connection lost! Roomba offline.
roomba.0 | 2023-08-07 10:43:14.696 | info | Connecting to Roomba (192.168.20.20)..
roomba.0 | 2023-08-07 10:43:14.693 | warn | Canvas not installed! Thus, no map drawings are possible. Please see installation instructions on Github (https://github.com/iobroker-community-adapters/ioBroker.roomba#installation).
roomba.0 | 2023-08-07 10:43:14.643 | info | starting. Version 1.1.4 in /opt/iobroker/node_modules/iobroker.roomba, node: v18.16.1, js-controller: 4.0.24
host.ioBroker | 2023-08-07 10:43:11.969 | info | instance system.adapter.roomba.0 started with pid 1496212

Password discovery also didn't work but I could do the manual way with the dorita980-script. The instance is running with a green indicator (connected to device or service) but in Objects -> Roomba.0.states._connected it still appears as "false"

I changed the Roomba.0.stated._connected to be a bool, since then the log looks cleaner, but doesn't help with connecting to the robot.

**Comment by fritz47110815** [comment]
Please see #143
