### ISSUE TITLE
Add support for iRobot Braava m6

### ISSUE THREAD

**Issue by wuliwux** [iobroker-community-adapters/ioBroker.roomba#20]
Hi, can you add Support for :

* Roomba Model: iRobot Braava m6
* Roomba Software Version: 3.10.8

Connection is ok, but States are empty.

![image](https://user-images.githubusercontent.com/1975703/95979420-e68f7800-0e1b-11eb-9f7f-e783ddb7cb7a.png)

greets

**Comment by lkn94** [comment]
Support for Braava Jet M6 would also be great for me. Thumbs up!

**Comment by wuliwux** [comment]
the adapter support the M6 there is a "feature" on the password detection.
to detect the correct connection settings use the "getpassword" command from

https://github.com/koalazak/dorita980#readme

and paste it to the adapter settings.

it works on my machine... ;-)

**Comment by wuliwux** [comment]
use the https://github.com/koalazak/dorita980#readme to get username and password and it works.
