### ISSUE TITLE
Firmware 3.5.62-95 - unable to get username/password

### ISSUE THREAD

**Issue by TheMiller2015** [iobroker-community-adapters/ioBroker.roomba#23]
Hello there. Is the firmware (3.5.62-95) support? I can't get username and password, neither via iobroker web ui nor via npm or docker. And yes, i followed the instructions exactly ;)

My iobroker instance is running in docker container. My robot is connected to my wifi, iobroker and roombar are in the same net / subnet. It is accessable via the iRobot-App but iobroker can't receive username and password. Other pieces of information (when not in wifi setup mode (flashing wifi symbol)) like model, blid, serialnumber can be retrieved. 

When I press and hold "spot" and "clean" while it the roomba is at the base, wifi starts blinking and the get-password npm says to press one key. After doing that it says sth. like "undefined" and times out after a while with that output:

> Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
Then press any key here...
node:events:304
      throw er; // Unhandled 'error' event
      ^
>
>Error: connect ETIMEDOUT 192.168.10.99:8883
>    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1129:16)
>Emitted 'error' event on TLSSocket instance at:
>   at emitErrorNT (node:internal/streams/destroy:194:8)
>    at emitErrorCloseNT (node:internal/streams/destroy:159:3)
>    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
>  errno: -110,
>  code: 'ETIMEDOUT',
>  syscall: 'connect',
>  address: '192.168.10.99',
>  port: 8883
>}

The roomba also is pingable from the docker container.

What can I do/test? Thanks in advance.

* Roomba Model: Roomba 675
* Roomba Software Version: 3.5.62-95

**Comment by TheMiller2015** [comment]
Hi, any news or isn't this repo supported any more? Tell me, how I can help and I'll try....

**Comment by wuliwux** [comment]
hi, have you tried it with the dorita way?

to detect the correct connection settings use the "getpassword" command from

https://github.com/koalazak/dorita980#readme

and paste it to the adapter settings.

**Comment by TheMiller2015** [comment]
Hi and sorry for the delay. Didn't expect to get an answer after that time. The mail may be ended in nirvana..... I tried all the ways (via iobroker, via docker, via general notebook with node.js, the javascript way, the npm way). 
Today, I did a factory reset at the roomba and the most I can see is the blid, but an error occurs while getting the password. Here is my output:

```
Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
Then press any key here...
Robot Data:
{
  ver: '3',
  hostname: 'Roomba-3162C21C60127610',
  robotname: 'Roomba',
  ip: '0.0.0.0',
  mac: 'xx:xx:xx:xx:xx:xx',
  sw: '3.5.62',
  sku: 'R675040',
  nc: 1,
  proto: 'mqtt',
  cap: { ota: 1, eco: 1, svcConf: 1 },
  blid: '3162C21C601******' <-- 
}
node:events:353
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:213:20)
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

That's all I got. Please, I somebody has some information. I also adjusted my mail settings to react in time ;) 
Thanks

**Comment by TheMiller2015** [comment]
Any progress on this?

**Comment by mcm1957** [comment]
Please check with newest version of adapter (1.2.1).
If issue still occure, please report your configuration (Adapter version, js-controller version, node, npm, OS).

If no response received within 30 days this issue might be closed.

**Comment by mcm1957** [comment]
no reaction received - lets close here.

If the problem still exists please post a commengt or open a new issue.
