### ISSUE TITLE
Roomba 692 works

### ISSUE THREAD

**Issue by Evil95** [iobroker-community-adapters/ioBroker.roomba#28]
* Roomba Model: 692
* Roomba Software Version: 3.5.62-95

Model 692 works, but no Map.
![Unbenannt](https://user-images.githubusercontent.com/45834434/103139943-12638f80-46e2-11eb-8c06-1bc0935b0a58.png)

**Comment by thost96** [comment]
Hi @Evil95,

I created a pr to add the Roomba 692 to the supported Models on the README. Thanks for your info!
