### ISSUE TITLE
Docked state wrong

### ISSUE THREAD

**Issue by Zefau** [iobroker-community-adapters/ioBroker.roomba#3]
https://github.com/Zefau/ioBroker.roomba/issues/28

**Comment by Zefau** [comment]
https://github.com/koalazak/dorita980/issues/111

**Comment by fungus75** [comment]
Hard to find out, where this issue is currently tracked because the given links above don't say anything to me.
Anyway: My Roomba 675 has exactly the same behaviour: when in the dock, the dock-status is false, when outside (cleaning), the dock-status is true.

**Comment by mcm1957** [comment]
Please check with newest version of adapter (1.2.1).
If issue still occure, please report your configuration (Adapter version, js-controller version, node, npm, OS).

If no response received within 30 days this issue might be closed.

**Comment by mcm1957** [comment]
According to discussion in the linked issues (especiallyhttps://github.com/koalazak/dorita980/issues/111) this state does MNOT represent the docking status (docked / not docked) but the information wheterh the roomba KNOWS where the docing station is.
