### ISSUE TITLE
Bug by getting Password!

### ISSUE THREAD

**Issue by Matze021986** [iobroker-community-adapters/ioBroker.roomba#30]
Hi there,
i'm using iRobot Braava M6 and this adapter works for this too!

But i've found a mistake by getting password using the function "getting IP & User Data".

I wondering, why my adapter was almost restarting every minute.

Have a look at the state: host: false; live: fasle; connect with roomba: true

After, let me think about 2 hours, i found the bug!

So, if you click "get IP Adress & User Data" and all status messages on the right sight are green, click on "show password".

Now hava a look at the last sign of the password! It is a control character! So, you have to delete the last sign of the password and after this click save and the adapter will work perfectly!

![thumbnail_IMG_2936](https://user-images.githubusercontent.com/77019999/103708228-758dd580-4fb0-11eb-9a66-7f9b3f3ff5c2.jpg)

**Comment by mcm1957** [comment]
Please check with newest version of adapter (1.2.1).
If issue still occure, please report your configuration (Adapter version, js-controller version, node, npm, OS).

If no response received within 30 days this issue might be closed.

**Comment by mcm1957** [comment]
no reaction received - lets close here.

If the problem still exists please post a commengt or open a new issue.
