### ISSUE TITLE
webinterface hangs on loading states

### ISSUE THREAD

**Issue by thost96** [iobroker-community-adapters/ioBroker.roomba#34]
Hi,

as many users reported in the forum (including me) that the web interface only shows loading states and isn't useable: 
- https://forum.iobroker.net/topic/7657/irobot-roomba-adapter/524
- https://forum.iobroker.net/post/507787 
- https://forum.iobroker.net/post/542497

So I'm creating an issue, so this can be tracked here. Thanks in advance!

**Comment by chrisSLDS** [comment]
Hey Guys, 
also got this problem...

original code:
 ```
getVersion:       function (callback) {
        if (!this._checkConnection('getVersion', arguments)) return;

        this._socket.emit('getVersion', function (version) {
            if (callback) callback(version);
        });
    },
    _checkAuth:       function (callback) {
        if (!this._isConnected) {
            console.log('No connection!');
            return;
        }
        //socket.io
        if (this._socket === null) {
            console.log('socket.io not initialized');
            return;
        }
        this._socket.emit('getVersion', function (version) {
            if (callback)
                callback(version);
        });
    },
```

but the response of the socket is:
```
{
  0: null
  1: "3.1.0"
  2: "web"
}
```

so 'version' will be always "null"

change the upper mentioned code to:

 ```
getVersion:       function (callback) {
        if (!this._checkConnection('getVersion', arguments)) return;

        this._socket.emit('getVersion', function (**nl,version,module**) {
            if (callback) callback(version);
        });
    },
    _checkAuth:       function (callback) {
        if (!this._isConnected) {
            console.log('No connection!');
            return;
        }
        //socket.io
        if (this._socket === null) {
            console.log('socket.io not initialized');
            return;
        }
        this._socket.emit('getVersion', function (**nl,version,module**) {
            if (callback)
                callback(version);
        });
    },
```

**Comment by thost96** [comment]
Hi @chrisSLDS, i tried your code and replaced the original one, but nothing has changed on the roomba webpage also after rebooting the instance and the whole node. Which adapter and js-controller version do you use?

**Comment by craptec** [comment]
Hi Guys,
as far as I understand this seems fixed but did it make it into the 1.1.2  release? Why is 1.1.2 not available trough the stable repo, yet?

Cheers
Max

**Comment by thost96** [comment]
Hi @craptec,

yes, this is fixed if you are using my pull request but didn't get merged yet, so it's not part of the 1.1.2 release.

**Comment by Apollon77** [comment]
Please try GitHub version

**Comment by thost96** [comment]
The GitHub version fixes this problem for me. Web interface now loads again without any errors.
