### ISSUE TITLE
stylesheet adapter.css not found

### ISSUE THREAD

**Issue by thost96** [iobroker-community-adapters/ioBroker.roomba#37]
The web UI tries to load the adapter.css stylesheet in https://github.com/iobroker-community-adapters/ioBroker.roomba/blob/0f3218e8fd7242dbd00cb96d0d425ff2aec98c32/admin/index_m.html#L5  which doesn't exists anymore. Was this content relocated anywhere else or isn't it needed anymore? 

If this isn't needed anymore it should be removed i think.

**Comment by mcm1957** [comment]
Please check with newest version of adapter (1.2.1).
If issue still occure, please report your configuration (Adapter version, js-controller version, node, npm, OS).

If no response received within 30 days this issue might be closed.

**Comment by mcm1957** [comment]
no reaction received - lets close here.

If the problem still exists please post a commengt or open a new issue.
