### ISSUE TITLE
Add support for Roombaroomba.0 2021-05-01 10:20:45.985 warn (6740) State value to set for "roomba.0.refreshedTimestamp" has wrong type "number" but has to be "string"

### ISSUE THREAD

**Issue by Grothesk242** [iobroker-community-adapters/ioBroker.roomba#45]
js-controller 3.3.x needs adjustments in the adapter code: 

roomba.0 2021-05-01 10:20:45.985 warn (6740) State value to set for "roomba.0.refreshedTimestamp" has wrong type "number" but has to be "string"

**Comment by thost96** [comment]
same for me with 

```  
roomba.0 | 2021-05-01 12:25:07.955 | warn | (2177) State value to set for "roomba.0.refreshedTimestamp" has wrong type "number" but has to be "string"
roomba.0 | 2021-05-01 12:25:07.954 | warn | (2177) State value to set for "roomba.0.states.signal" has wrong type "number" but has to be "string"
```
just as reference: https://github.com/ioBroker/ioBroker.js-controller/issues/1299

**Comment by JackDaniel007** [comment]
05-16 15:33:59.570 | info | (43797) State value to set for "roomba.0.statistics.time.hOnDock" has to be type "string" but received type "number"

**Comment by Apollon77** [comment]
Please try GitHub version. Restart adaoter afterwards and delete affected objects manually before. they will be recreated

**Comment by thost96** [comment]
After updating to the GitHub version, stopping the instance and deleting the whole roomba.0 object tree, I still got these errors/warning: 

<html>
<body>


roomba.0 | 2021-07-16 17:45:12.985 | warn | Object of state "roomba.0.statistics.missions" is missing the required property "common.type"
-- | -- | -- | --
roomba.0 | 2021-07-16 17:45:12.985 | warn | Object of state "roomba.0.statistics.time" is missing the required property "common.type"
roomba.0 | 2021-07-16 17:45:12.985 | warn | Object of state "roomba.0.statistics" is missing the required property "common.type"
roomba.0 | 2021-07-16 17:45:12.985 | warn | Object of state "roomba.0.states" is missing the required property "common.type"
roomba.0 | 2021-07-16 17:45:12.947 | warn | Object of state "roomba.0.device.preferences" is missing the required property "common.type"
roomba.0 | 2021-07-16 17:45:12.947 | warn | Object of state "roomba.0.device.versions" is missing the required property "common.type"
roomba.0 | 2021-07-16 17:45:12.947 | warn | Object of state "roomba.0.device.network" is missing the required property "common.type"
roomba.0 | 2021-07-16 17:45:12.947 | warn | Object of state "roomba.0.device" is missing the required property "common.type"
roomba.0 | 2021-07-16 17:45:12.947 | warn | Object of state "roomba.0.missions.schedule" is missing the required property "common.type"
roomba.0 | 2021-07-16 17:45:12.946 | warn | Object of state "roomba.0.missions.current" is missing the required property "common.type"
roomba.0 | 2021-07-16 17:45:12.946 | warn | Object of state "roomba.0.missions" is missing the required property "common.type"
roomba.0 | 2021-07-16 17:45:12.945 | warn | Object of state "roomba.0.commands.last" is missing the required property "common.type"
roomba.0 | 2021-07-16 17:45:12.944 | warn | Object of state "roomba.0.commands" is missing the required property "common.type"


</body>
</html>
<html>
<body>


roomba.0 | 2021-07-16 17:47:29.052 | info | State value to set for "roomba.0.statistics.missions.failed" has to be type "string" but received type "number"
-- | -- | -- | --
roomba.0 | 2021-07-16 17:47:29.052 | info | State value to set for "roomba.0.statistics.missions.succeed" has to be type "string" but received type "number"
roomba.0 | 2021-07-16 17:47:29.051 | info | State value to set for "roomba.0.statistics.missions.total" has to be type "string" but received type "number"
roomba.0 | 2021-07-16 17:47:29.043 | info | State value to set for "roomba.0.statistics.time.nDocks" has to be type "string" but received type "number"
roomba.0 | 2021-07-16 17:47:29.043 | info | State value to set for "roomba.0.statistics.time.nNimhChrg" has to be type "string" but received type "number"
roomba.0 | 2021-07-16 17:47:29.043 | info | State value to set for "roomba.0.statistics.time.nLithChrg" has to be type "string" but received type "number"
roomba.0 | 2021-07-16 17:47:29.043 | info | State value to set for "roomba.0.statistics.time.estCap" has to be type "string" but received type "number"
roomba.0 | 2021-07-16 17:47:29.043 | info | State value to set for "roomba.0.statistics.time.nAvail" has to be type "string" but received type "number"
roomba.0 | 2021-07-16 17:47:29.042 | info | State value to set for "roomba.0.statistics.time.avgMin" has to be type "string" but received type "number"
roomba.0 | 2021-07-16 17:47:29.038 | info | State value to set for "roomba.0.states.battery" has to be type "string" but received type "number"
roomba.0 | 2021-07-16 17:47:28.997 | info | State value to set for "roomba.0.device.versions.hardwareRev" has to be type "string" but received type "number"
roomba.0 | 2021-07-16 17:47:28.996 | info | State value to set for "roomba.0.device.network.dhcp" has to be type "string" but received type "boolean"
roomba.0 | 2021-07-16 17:47:28.995 | info | State value to set for "roomba.0.commands.last.timestamp" has to be type "string" but received type "number"


</body>
</html>

**Comment by Apollon77** [comment]
@JBSullivan Please try again Github version

**Comment by Apollon77** [comment]
Any thing left here??
