### ISSUE TITLE
json Tabelle entspricht nicht der Norm

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.roomba#5]
Die vom Roomba ausgegebene json Tabelle scheint durch die Schachtelung der Werte in Klammern {} nicht der "json Norm" zu entsprechen. Aus diesem Grund kommt es im VIS Widget von ioBroker zu einer falschen Darstellung.

sie hier: https://forum.iobroker.net/topic/15965/wie-wird-das-widget-json-table-eingestellt-formatiert/37

**Comment by mcm1957** [comment]
Please check with newest version of adapter (1.2.1).
If issue still occure, please report your configuration (Adapter version, js-controller version, node, npm, OS).
And please add an example of the json data causing the problem.

If no response received within 30 days this issue might be closed.

**Comment by mcm1957** [comment]
no reaction - lets close.

Please drop a note or open a new issue if the problem still exists.
