### ISSUE TITLE
Add support for Roomba

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.roomba#50]
Seit dem Update auf js-controller 3.3.11 und/oder Admin 5.0.32 ist die Webseite des Sauger nicht mehr erreichbar.

![image](https://user-images.githubusercontent.com/44617472/119314218-c9097300-bc74-11eb-9c35-6680cb86971c.png)

* Roomba Model: 960
* Roomba Software Version: v2.4.13-119
* Roomba NavSWfVer: 01.12.01#1

**Comment by thost96** [comment]
I have the same problem with js-controller 3.3.11 and admin 5.1.0 and roomba 1.1.2

**Comment by Apollon77** [comment]
Please try github version

**Comment by thost96** [comment]
The GitHub version fixes this problem for me. Web interface now loads again without any errors. Only thing I noticed is, that the web interface is opened on the IP address of the configured Roomba device and not on the IP or hostname of ioBroker. So by default this doesn't work if you didn't change it.

**Comment by JBSullivan** [comment]
Zur Erinnerung ;)

`roomba.0	2021-07-16 17:17:09.743	info	(15004) State value to set for "roomba.0.statistics.missions.failed" has to be type "string" but received type "number"
roomba.0	2021-07-16 17:17:09.743	info	(15004) State value to set for "roomba.0.statistics.missions.succeed" has to be type "string" but received type "number"
roomba.0	2021-07-16 17:17:09.742	info	(15004) State value to set for "roomba.0.statistics.missions.total" has to be type "string" but received type "number"
roomba.0	2021-07-16 17:17:09.742	info	(15004) State value to set for "roomba.0.statistics.time.nDocks" has to be type "string" but received type "number"
roomba.0	2021-07-16 17:17:09.742	info	(15004) State value to set for "roomba.0.statistics.time.nNimhChrg" has to be type "string" but received type "number"
roomba.0	2021-07-16 17:17:09.741	info	(15004) State value to set for "roomba.0.statistics.time.nLithChrg" has to be type "string" but received type "number"
roomba.0	2021-07-16 17:17:09.741	info	(15004) State value to set for "roomba.0.statistics.time.estCap" has to be type "string" but received type "number"
roomba.0	2021-07-16 17:17:09.740	info	(15004) State value to set for "roomba.0.statistics.time.nAvail" has to be type "string" but received type "number"
roomba.0	2021-07-16 17:17:09.740	info	(15004) State value to set for "roomba.0.statistics.time.avgMin" has to be type "string" but received type "number"
roomba.0	2021-07-16 17:17:09.739	info	(15004) State value to set for "roomba.0.states.battery" has to be type "string" but received type "number"
roomba.0	2021-07-16 17:17:09.737	info	(15004) State value to set for "roomba.0.device.versions.hardwareRev" has to be type "string" but received type "number"
roomba.0	2021-07-16 17:17:09.736	info	(15004) State value to set for "roomba.0.device.network.dhcp" has to be type "string" but received type "boolean"
roomba.0	2021-07-16 17:17:09.735	info	(15004) State value to set for "roomba.0.commands.last.timestamp" has to be type "string" but received type "number"`

**Comment by thost96** [comment]
@JBSullivan maybe wrong issue? Please see #45

**Comment by Apollon77** [comment]
@thost96 Can you do a new issue please for "localLink is not working" ... this is a bit bigger because placeholders and variables frpm adapter overlap ... nothing I will do now ...
