### ISSUE TITLE
Falsches state - js-controller 3.3.x

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.roomba#56]
Auf bitte von @Apollon77 lege ich hier mal ein Issue zu dem letzten verbliebenen falschen state an. Vielleicht kannst du @Zefau da nochmal ein Auge drauf werfen.

Siehe hier die ersten beiden Zeilen. Im übrigen funktionieren nach den gestrigen Updates bei deinen beiden Adaptern die Webinterfaces wieder. ->  https://forum.iobroker.net/topic/7657/irobot-roomba-adapter/661

`roomba.0	2021-07-20 20:03:29.694	info	(11856) State value to set for "roomba.0.states._connected" has to be type "string" but received type "boolean"
roomba.0	2021-07-20 20:03:29.693	info	(11856) State value to set for "roomba.0.states._connected" has to be type "string" but received type "boolean"
roomba.0	2021-07-20 20:03:29.691	debug	(11856) Updated state states._connected to value false (from null).
roomba.0	2021-07-20 20:03:29.690	debug	(11856) Updated state states._connected to value false (from null).
roomba.0	2021-07-20 20:03:29.685	debug	(11856) {"errno":-4077,"code":"ECONNRESET","syscall":"read"}
roomba.0	2021-07-20 20:03:29.685	warn	(11856) Unknown error! Please see debug log for details.
roomba.0	2021-07-20 20:03:29.685	info	(11856) Roomba Connection closed.
roomba.0	2021-07-20 20:03:29.684	warn	(11856) Connection lost! Roomba offline.
roomba.0	2021-07-20 20:03:13.317	debug	(11856) system.adapter.admin.0: logging true
roomba.0	2021-07-20 20:03:11.759	debug	(11856) Updated state info.connection to value true (from null).
roomba.0	2021-07-20 20:03:11.751	debug	(11856) Updated state info.connection to value false (from null).
roomba.0	2021-07-20 20:03:11.651	info	(11856) Connecting to Roomba (10.122.60.10)..
roomba.0	2021-07-20 20:03:11.597	info	(11856) starting. Version 1.1.4 in C:/iobroker/GLT/node_modules/iobroker.roomba, node: v14.16.0, js-controller: 3.3.14`

**Comment by mcm1957** [comment]
siehe #104
