### ISSUE TITLE
Add support for Braava M6 Jet - Water

### ISSUE THREAD

**Issue by SKB-CGN** [iobroker-community-adapters/ioBroker.roomba#73]
* Roomba Model: iRobot Braava M6 Jet
* Roomba Software Version:

Hi, is someone able, to implement the water status of a iRobot Braava M6 Jet?

The value for this is included in the RAW Data: notReady":31" means empty and 0 means full.

Thank you!

**Comment by mcm1957** [comment]
Please check with newest version of adapter (1.2.1).
If issue still occure, please report your configuration (Adapter version, js-controller version, node, npm, OS).

If no response received within 30 days this issue might be closed.

**Comment by mcm1957** [comment]
no reaction received - lets close here.

If the problem still exists please post a commengt or open a new issue.
