### ISSUE TITLE
Cleaned Square Meter always false

### ISSUE THREAD

**Issue by SKB-CGN** [iobroker-community-adapters/ioBroker.roomba#76]
Hi,
can someone please fix the line 723 as the Data is not coming from this object anymore.
The new one is: JSON.bbrun.sqft

Thanks!

**Comment by mcm1957** [comment]
Please check with newest version of adapter (1.2.1).
If issue still occure, please report your configuration (Adapter version, js-controller version, node, npm, OS).

If no response received within 30 days this issue might be closed.

**Comment by mcm1957** [comment]
no reaction received - lets close here.

If the problem still exists please post a commengt or open a new issue.
