### ISSUE TITLE
Roomba 671 verbindet sich nicht mit Adapter

### ISSUE THREAD

**Issue by motioneyeosuser** [iobroker-community-adapters/ioBroker.roomba#83]
* Roomba Model:  671
* Roomba Software Version: 1.1.4

roomba.0
Verbunden mit Host: ja
Lebenszeichen: ja
Verbunden mit Gerät oder Dienst: nein

Roomba 671
WLAN LED blinkt nach Beep

Fehlermeldung nach Verbindungsversuch:
Connecting to adapter..
Connected to adapter. Retrieving credentials..
Retrieve credentials..
Could not retrieve credentials! MAKE SURE TO PRESS AND HOLD --HOME-- BUTTON 2 SECONDS (not the clean button)! ({"errno":"EADDRINUSE","code":"EADDRINUSE","syscall":"bind","address":"0.0.0.0","port":5678})
Get IP address..
Could not retrieve IP address! (bind EADDRINUSE 0.0.0.0:5678)

**Comment by SvenK84** [comment]
Ich hatte das gleiche Problem bei meinem Roomba 980.
Was geholfen hat ist, die IP vorab manuell einzutragen und erst danach die Anleitung zu befolgen. Dann hat er die Zugangsdaten erkannt.

**Comment by mcm1957** [comment]
Please check with newest version of adapter (1.2.1).
If issue still occure, please report your configuration (Adapter version, js-controller version, node, npm, OS).

If no response received within 30 days this issue might be closed.

**Comment by mcm1957** [comment]
no reaction - will close here.
Please open a new issue if problem still occures and add all availbale logs and version information
